from fastapi import APIRouter, HTTPException

from models.session import SessionCreateRequest, SessionCreateResponse
from models.action import Action
from models.agent_context import AgentContext

from services import session_service, context_service, agent_service, action_service
from storage import memory_store

router = APIRouter(prefix="/sessions", tags=["sessions"])


@router.post("", response_model=SessionCreateResponse)
def create_session(payload: SessionCreateRequest):
    """
    Register a new agent task/session.

    The session_id MUST be generated by the Browser Extension, not by this
    backend. This endpoint only registers it and initializes empty state.
    """
    return session_service.create_session(payload)


@router.get("/{session_id}/context", response_model=AgentContext)
def get_context(session_id: str):
    """
    Build and return the current AgentContext for debugging/integration.

    Note: this returns visual context METADATA only, never raw image bytes.
    """
    return context_service.build_agent_context(session_id)


@router.post("/{session_id}/next-action", response_model=Action)
def next_action(session_id: str):
    """
    Central endpoint: assemble AgentContext, ask the agent service for the
    next Action, validate it, store it, and return it to the extension.
    """
    session_service.require_session(session_id)

    context = context_service.build_agent_context(session_id)
    raw_action = agent_service.decide_next_action(context)
    validated_action = action_service.validate_action(raw_action, context.page_state)

    memory_store.update_latest_action(session_id, validated_action)
    return validated_action


@router.get("/{session_id}/latest-action", response_model=Action)
def latest_action(session_id: str):
    """Return the most recently computed action for this session, if any."""
    session_service.require_session(session_id)
    action = memory_store.get_latest_action(session_id)
    if action is None:
        raise HTTPException(status_code=404, detail=f"No action has been computed yet for session '{session_id}'.")
    return action
