"""
Session lifecycle models.

IMPORTANT: The session_id is always generated by the Browser Extension.
The backend never generates or reassigns session identifiers -- it only
registers and looks them up.
"""

from pydantic import BaseModel, Field


class SessionCreateRequest(BaseModel):
    """Body of POST /sessions."""

    session_id: str = Field(..., description="UUID generated by the Browser Extension. Backend does NOT generate this.")
    task: str = Field(..., description="Natural-language description of the task/goal for this session")


class SessionCreateResponse(BaseModel):
    session_id: str
    task: str
    status: str
    message: str
